apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: accounts-event-listener
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - name: github-push
      interceptors:
        - ref:
            name: github
          params:
            - name: eventTypes
              value: ["push"]
            - name: secretRef
              value:
                secretName: github-webhook-secret
                secretKey: webhook-secret
      bindings:
        - ref: accounts-trigger-binding
      template:
        ref: accounts-trigger-template
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: accounts-trigger-binding
spec:
  params:
    - name: gitrevision
      value: $(body.head_commit.id)
    - name: gitrepositoryurl
      value: $(body.repository.clone_url)
    - name: gitbranch
      value: $(body.ref)
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: accounts-trigger-template
spec:
  params:
    - name: gitrevision
      description: The git revision
    - name: gitrepositoryurl
      description: The git repository URL
    - name: gitbranch
      description: The git branch
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: accounts-cd-run-
      spec:
        pipelineRef:
          name: accounts-cd-pipeline
        params:
          - name: repo-url
            value: $(tt.params.gitrepositoryurl)
          - name: branch
            value: $(tt.params.gitbranch)
        workspaces:
          - name: source
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
          - name: dockerconfig
            secret:
              secretName: docker-credentials
